---
title: "bd_result_wrangling"
format: html
editor: source
---

## Load Packages

```{r}

if(!require(librarian)){
  install.packages(librarian)
  library(librarian)
}

shelf(tidyverse, here, janitor, readxl, parsedate, stringr, lubridate, stringi)

```

## Loop for Read in
```{r}
files <- list.files(here("raw_data"))

for (i in 1:length(files)) {
  
  
  x <- read_excel(here("raw_data", files[i]), sheet = "Results", col_names = F) %>% 
    slice(c(43:331)) %>% 
    row_to_names(1) %>% 
    clean_names()
    
  
  assign(files[i], x)
  
  
}


qPCR_RIBBiTR_Penn2022_28July2023_Plate1_RESULTS.xls <- qPCR_RIBBiTR_Penn2022_28July2023_Plate1_RESULTS.xls %>% 
  mutate(qpcr_date = as_date("2023-08-22"),
         extraction_date = as_date("2023-07-28"))

RIBBiTR_qPCR_Penn2022_21July2023_Plate1_RERUN_RESULTS.xls <- RIBBiTR_qPCR_Penn2022_21July2023_Plate1_RERUN_RESULTS.xls %>% 
  mutate(qpcr_date = as_date("2023-09-05"),
         extraction_date = as_date("2023-07-21"))

RIBBiTR_qPCR_Penn2022_28July2023_Plate2_RBV_RESULTS.xls <- RIBBiTR_qPCR_Penn2022_28July2023_Plate2_RBV_RESULTS.xls %>% 
    mutate(qpcr_date = as_date("2023-09-10"),
           extraction_date = as_date("2023-07-28"))

PaBdSwabs2022_plate1RERUN_03212023_results.xlsx <- PaBdSwabs2022_plate1RERUN_03212023_results.xlsx %>% 
  mutate(qpcr_date = as_date("2023-03-21"),
          extraction_date = "")

PaBdSwabs2022_04062023_Plate2_Results.xlsx <- PaBdSwabs2022_04062023_Plate2_Results.xlsx %>% 
  mutate(qpcr_date = as_date("2023-04-06"),
         extraction_date = "")

  
  

```

## Wrangle Data
```{r}

qpcr_2022 <- rbind(qPCR_RIBBiTR_Penn2022_28July2023_Plate1_RESULTS.xls, RIBBiTR_qPCR_Penn2022_28July2023_Plate2_RBV_RESULTS.xls,
                   RIBBiTR_qPCR_Penn2022_21July2023_Plate1_RERUN_RESULTS.xls, PaBdSwabs2022_plate1RERUN_03212023_results.xlsx,
                   PaBdSwabs2022_04062023_Plate2_Results.xlsx) %>% 
  filter(target_name == 'Bd') %>% 
  select(!c(y_intercept:tholdfail)) %>% 
  select(!c(omit, target_name, task, reporter, quencher, well, ct, ct_sd, quantity, quantity_sd, well_position)) %>% 
  rename(bd_swab_id = sample_name,
         average_ct = ct_mean,
         average_copy_number = quantity_mean) %>% 
  mutate(extract_lab = "rz_lab",
         qpcr_lab = "rz_lab",
         standard = "pisces",
         master_mix = "bioline",
         qpcr_machine = "quantstudio_3",
         extraction_kit = "qiagen_dneasy",
         replicate = "singley",
         result = if_else(!is.na(average_ct), "p", "n"),
         swab_type = "mw113",
         total_volume_uL = 200,
         dillution_factor = "1:1",
         volume_template_dna_uL = 5) %>% 
  filter(!str_detect(bd_swab_id, "Pisces Bd/Bsal"),
         !str_detect(bd_swab_id, "Positive"),
         !str_detect(bd_swab_id, "Negative"),
         !str_detect(bd_swab_id, "neg"),
         !str_detect(bd_swab_id, "Extract Control")) %>% 
  mutate(bd_swab_id = if_else(bd_swab_id == "2022-05-05 Phelps pscr #11; skin tag on throat",
                              "2022-05-05 Phelps pscr #11", bd_swab_id),
         comments = "",
         comments = if_else(str_detect(bd_swab_id, "BdSwab"), "Swab stored in RNA shield", comments),
         comments = if_else(str_detect(bd_swab_id, "DrySwab"), 
                            "Naming convention yet to be standardized, Non-intuitive convention but correct", comments)) %>% 
  mutate(bd_swab_id = str_to_lower(str_replace_all(bd_swab_id, " ", "-")),
         bd_swab_id = str_replace_all(bd_swab_id, "#", ""),
         bd_swab_id = str_remove(bd_swab_id, "-(?=\\d+$)"),
         bd_swab_id = if_else(bd_swab_id == "2022-05-11-admin-toad-sp.19", "2022-05-11-admin-toad19", bd_swab_id),
         bd_swab_id = if_else(bd_swab_id == "2022-05-12rv-hyve22", "2022-05-12-rv-hyve22", bd_swab_id)) %>% 
  mutate(bd_swab_id = if_else(bd_swab_id == "bdswab00067", "bdswab000067", bd_swab_id),
         bd_swab_id = if_else(bd_swab_id == "bdswab00068", "bdswab000068", bd_swab_id),
         bd_swab_id = if_else(bd_swab_id == "bdswab00069", "bdswab000069", bd_swab_id),
         bd_swab_id = if_else(bd_swab_id == "bdswab00083", "bdswab000083", bd_swab_id),
         bd_swab_id = if_else(bd_swab_id == "bdswab00084", "bdswab000084", bd_swab_id),
         bd_swab_id = if_else(bd_swab_id == "bdswab00085", "bdswab000085", bd_swab_id),
         bd_swab_id = if_else(bd_swab_id == "2022-04-19-admin-raca9", "2022-05-19-admin-raca9", bd_swab_id),
         bd_swab_id = if_else(bd_swab_id == "2022-05-18⊐admin-rapi16", "2022-05-18-admin-rapi16", bd_swab_id),
         bd_swab_id = if_else(bd_swab_id == "2022-05-12-rv-hyve10", "2022-05-12-rv-hyve18", bd_swab_id),
         bd_swab_id = if_else(bd_swab_id == "2022-05-19-admin-raca27", "2022-05-19-admin-rapi27", bd_swab_id),
         average_copy_number= as.numeric(average_copy_number),
         average_ct = as.numeric(average_ct),
         average_copy_number = if_else(is.na(average_copy_number), 0, average_copy_number)) %>% 
  filter(!bd_swab_id %in% c("neg-3.28.23", "neg-2.21.23", "pos-2.21.23", "pos-3.27.23")) %>% 
  group_by(bd_swab_id) %>% 
  unique()

update <- str_detect(qpcr_2022$bd_swab_id, "^dry\\d+")

qpcr_2022$bd_swab_id[update] <- str_replace(qpcr_2022$bd_swab_id[update], "^dry", "dryswab")


# miss_ids <- d %>%
#   select(bd_swab_id) %>%
#   #filter(str_detect(bd_swab_id, "BdSwab")) %>%
#   write_csv(here("clean_tables", "last_id_joins.csv"))



write_csv(qpcr_2022, here("clean_tables", "penn_22-23_bd_results.csv"))
```

